# Default bridge network between containers
networks:
  vulx:
    name: "vulx"
# (dependency chain) SQL → API → Inngest → App (frontend)
services:
  sql:
    container_name: "sql"
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d local -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - vulx

  inngest:
    container_name: "inngest"
    image: inngest/inngest:v1.11.5
    command: "inngest dev"
    environment:
      - INNGEST_DEV=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8288"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "8288:8288" # Dashboard will be available here
      - "8289:8289" # Connect gateway for WebSocket connections
    networks:
      - vulx
  api:
    container_name: "vulx-api"
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - INNGEST_DEV=1
      - INNGEST_DEV_SERVER_URL=http://inngest:8288
    ports:
      - "8080:8080"
    networks:
      - vulx
    depends_on:
      sql:
        condition: service_healthy
      inngest:
        condition: service_healthy

  app:
    container_name: "vulx-app"
    build:
      context: app
      dockerfile: Dockerfile.dev # for local test use dev file
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - vulx-app-node-modules:/app/node_modules
    networks:
      - vulx
    depends_on:
      api:
        condition: service_started

volumes:
  pgdata:
  vulx-app-node-modules:
