# Default bridge network between containers
networks:
  vulx:
    name: "vulx"

services:
  sql:
    container_name: "sql"
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d local -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - vulx

  api:
    container_name: "vulx-api"
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - vulx
    depends_on:
      sql:
        condition: service_healthy

  app:
    container_name: "vulx-app"
    build:
      context: app
      dockerfile: Dockerfile.dev # for local test use dev file
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - vulx-app-node-modules:/app/node_modules
    networks:
      - vulx
    depends_on:
      api:
        condition: service_started

volumes:
  pgdata:
  vulx-app-node-modules:
